name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"  # Once every 24 hours
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Create dist directory to store the generated SVGs
      - name: Create dist directory
        run: mkdir -p dist

      # Generate snake game from GitHub user contributions graph and output SVGs
      - name: Generate GitHub contribution snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Automatically uses your GitHub username

      # Ensure that the output branch exists (create it if necessary)
      - name: Check if output branch exists
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/output; then
            echo "Branch output exists."
          else
            echo "Branch output does not exist. Creating output branch."
            git checkout -b output
            git push origin output
          fi

      # Push the generated SVG to the 'output' branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output  # This is the branch where the SVG will be pushed
          build_dir: dist  # The 'dist' folder where the SVG is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticates the push
