name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"  # Once every 24 hours
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push to the main branch (optional)
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Create dist directory to store the generated SVGs
      - name: Create dist directory
        run: mkdir -p dist

      # Generates a snake game from a GitHub user's contribution graph and outputs SVG animations
      - name: Generate GitHub contribution snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Automatically uses your GitHub username

      # Push the generated SVG to the 'output' branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4  # Updated version
        with:
          target_branch: output  # This is the branch where the SVG will be pushed
          build_dir: dist  # The 'dist' folder where the SVG is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticates the push
