name: Metrics2
on:
  # Schedule updates (each day)
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      # Step to get the current year and set it as an environment variable
      - name: Get current year
        id: get-year
        run: echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mantavyam
          template: classic
          base: activity, community, repositories
          config_display: regular
          config_timezone: Asia/Calcutta
          
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Habits plugin
          plugin_habits: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Notable contributions plugin
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_self: yes
          plugin_notable_types: commit
